engines:
  duplication:
    enabled: false
  structure:
    enabled: false
  sonar-java:
    enabled: true
    channel: beta
    config:
      languages:
        - java
      tests_patterns:
        - "**/test/**"
ratings:
  paths:
    - "**.java"
exclude_paths:
  - "**Template**"
  - "**.js"
  - "**.jsx"
  - "**.rb"
  - "**.py"
